# Generated by Django 4.0.6 on 2022-08-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.meeting')),
            ],
            options={
                'verbose_name': 'Заявка на курс с сайта',
                'verbose_name_plural': 'Заявки на курс с сайта',
                'ordering': ['-date'],
            },
        ),
    ]
